env: spread

env_args:
  N: 3
  local_ratio: 0.1
  shuffle: True


test_greedy: True
test_nepisode: 32
test_interval: 10000
log_interval: 10000
runner_log_interval: 10000
learner_log_interval: 10000
t_max: 50000000
save_model: True
save_model_interval: 50000

name: "spread_n_2_local_ratio_1e-1_shuffle_extended_15"