env: spread

env_args:
  N: 2
  local_ratio: 0


test_greedy: True
test_nepisode: 32
test_interval: 10000
log_interval: 10000
runner_log_interval: 10000
learner_log_interval: 10000
t_max: 7500000
save_model: True
save_model_interval: 50000
obs_agent_id: True

name: "spread_n_2_no_collide_w_agent_id_extended"