env: spread

env_args:
  N: 3

test_greedy: True
test_nepisode: 32
test_interval: 10000
log_interval: 10000
runner_log_interval: 10000
learner_log_interval: 10000
t_max: 2050000
save_model: True
save_model_interval: 50000
checkpoint_path: /home/aru/fyp/pymarl/results/models/coma__2022-01-27_19-19-38
