env: spread

env_args:
  N: 2
  # no collide
  local_ratio: 0


test_greedy: True
test_nepisode: 32
test_interval: 10000
log_interval: 10000
runner_log_interval: 10000
learner_log_interval: 10000
# train for 5 million time steps
t_max: 5000000
save_model: True
save_model_interval: 50000

# narrow
rnn_hidden_dim: 16

name: "spread_n_2_narrow_no_collide"