env: spread

env_args:
  N: 2

test_greedy: True
test_nepisode: 32
test_interval: 10000
log_interval: 10000
runner_log_interval: 10000
learner_log_interval: 10000
t_max: 50000000
save_model: True
save_model_interval: 50000

name: "spread_n_2_extended_50"